# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('recordTime', models.DateField(auto_now=True)),
                ('showPicture', models.ImageField(upload_to='showImg')),
                ('articleDes', models.CharField(max_length=300)),
                ('articleDetial', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTarget',
            fields=[
                ('targetName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.ArticleTarget'),
        ),
    ]
